
services:
- type: web
  name: hello
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  envVars:
  - fromGroup: envvars
  - key: PROMPT_FOR_THIS_IN_ENVVAR
    sync: false

envVarGroups:
- name: envvars
  envVars:
  - key: PROMPT_FOR_THIS_IN_ENVVAR_GROUP
    sync: false
